spring:
  application:
    name: SHOES SHOP
  profiles:
    active: ${ENV:dev}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${DATABASE_PASSWORD:root}
    username: ${DATABASE_USERNAME:root}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/shoes_shop}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  flyway:
    baseline-on-migrate: true
server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${SECRET_KEY:secret}
  token-validity: ${TOKEN_VALIDITY:604800000}
